#
# Blog Settings
#
author: Felipe Leusin
description: 
url: http://felipeleusin.com
title: Felipe Leusin
subtitle: Coding music and what else comes to mind
gravatar_url: http://www.gravatar.com/avatar/2249dc83471a49a7d5eb8945dcc06795.png
#subscribe_rss: http://feeds.haacked.com/haacked

# Github repositories
github_user: felipeleusin
github_repo_url: https://github.com/felipeleusin/felipeleusin.com/

# Twitter
twitter_user: whymclovin
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: 
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-177588-1


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories